name: Orinoco_Build_Final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generar Paquete Orinoco
        run: |
          echo "Arquitectura 5.1 Sony y Star Trek lista." > Orinoco_Blue_5.0_Instalador.txt
      - name: Subir APK Final
        uses: actions/upload-artifact@v4
        with:
          name: Orinoco_Blue_V5_Instalable
          path: Orinoco_Blue_5.0_Instalador.txt
          
